### ISSUE TITLE
Fails after initial connection

### ISSUE THREAD

**Issue by jon798** [cdpuk/givenergy-local#105]
Hello,

* Inverter model & generation: GIV-HY3.6. (Gen 3 hybrid 3.6 kW)
* Inverter firmware version: D0.309-A0.309
* Battery firmware version: 4007
* Home Assistant integration version: 2.1.0, running on HA version 2024.11.2

## Describe the bug

When the integration starts, devices and sensors are created for the inverter and the 3x 5.12kW Gen 3 batteries that are installed. Shortly afterwards (e.g. 10 seconds), the sensors all report 'unavailable' and don't recover.  Reloading the integration repopulates the sensors for a few more seconds until they again all become 'unavailable'.

The GivEnergy cloud portal and iOS GivEnergy app appear to work as expected.

GivTCP works ok, but in it's logs reports "10 failed inverter reads in a row, so removing regCache to force..." intermittently (can be 6 hours or 10 minutes apart), also seeing the occasional "Battery object empty so skipping".

## Debug log

[home-assistant_givenergy_local_2024-11-21T08-49-07.360Z.log](https://github.com/user-attachments/files/17842795/home-assistant_givenergy_local_2024-11-21T08-49-07.360Z.log)

If there's anything else I can do to help diagnose/troubleshoot, please let me know.

Thanks!

**Comment by jon798** [comment]
To follow up on this - everything appears to have sprung into place after GivEnergy pushed through a battery firmware update from v4004 to v4007. So probably can close this issue.

**Comment by cdpuk** [comment]
Good to know. Thanks for the update.
