### ISSUE TITLE
Errors after v1.6.2

### ISSUE THREAD

**Issue by ianfretwell** [cdpuk/givenergy-local#30]
Since upgrading to v1.6.2 I seem to be having issues with the integration - primarily noticed by the uploads to PVOutput just stopping. A restart of HA brings things back to life but then it just seems to stop again.

It might be HA itself of course but it's only happened since v1.6.2 was installed.

HA is 2023.2.3
GivEnergy AC3 Inverter with GivBat 5.2 battery

Errors in the logs include:-

**1.**
Logger: givenergy_modbus
Source: /usr/local/lib/python3.10/site-packages/givenergy_modbus/modbus.py:52
First occurred: 15:44:12 (4 occurrences)
Last logged: 16:50:12

Modbus Error: [Input/Output] No Response received from the remote unit/Unable to decode response
NoneType: None

**2.**
This error originated from a custom integration.

Logger: givenergy_modbus
Source: custom_components/givenergy_local/coordinator.py:64
Integration: GivEnergy Local (documentation, issues)
First occurred: 14:34:23 (4 occurrences)
Last logged: 15:44:12

Did not receive expected response type: ReadInputRegistersResponse != NoneType
Did not receive expected response type: ReadInputRegistersResponse != ErrorResponse
Did not receive expected response type: ReadHoldingRegistersResponse != ErrorResponse
Did not receive expected response type: ReadHoldingRegistersResponse != ModbusIOException

**3.**
This error originated from a custom integration.

Logger: givenergy_modbus
Source: custom_components/givenergy_local/coordinator.py:69
Integration: GivEnergy Local (documentation, issues)
First occurred: 15:07:10 (14 occurrences)
Last logged: 18:11:13

Did not receive expected response type: ReadInputRegistersResponse != ErrorResponse
Returned base register (60) does not match that from request (0).
Did not receive expected response type: ReadInputRegistersResponse != ModbusIOException
Returned base register (0) does not match that from request (60).
Returned base register (60) does not match that from request (180).

Thanks,
Ian

**Comment by cdpuk** [comment]
The modbus library has not changed in v1.6.2, and I've not had any other reports of problems with that specific version.

Unfortunately, as per the README, those sorts of errors are not usually something that can be fixed with a code change here. It's nearly always something to do with the local environment/network or perhaps some flaky GivEnergy firmware.
