### ISSUE TITLE
Query as opposed to issue...

### ISSUE THREAD

**Issue by ianfretwell** [cdpuk/givenergy-local#44]
Hi,

Can I ask what the "Remaining Capacity" figure actually represents please ?

I have a 5.2 battery - currently showing the following figures:-

Charge                        95%     _(never seen this go beyond 95%)_
Battery Percent           100%
Remaining Capacity    4.852kWh

Shouldn't that figure actually be 5.2kWh    OR   4.16kWh (i.e. 80% DOD of the full 5.2)  ?

I have the default 4% reserve and when the battery stops discharging the remaining capacity is uaullu around 0.81kWh.  So I suppose 4.85 - 0.81 = 4.04 is fairly close to 4.16 ?

Any help or confirmation you could offer would be great.

Thanks,
Ian

**Comment by cdpuk** [comment]
Remaining capacity is reported from the battery in Ah. This gets multiplied by the current voltage and scaled to give a value in kWh. How well these values map to the real world is a bit of a guess. They're probably close enough for most people but I imagine battery characteristics vary depending on a number of conditions. Then there's probably a difference between the marketing blurb and the real capabilities of the battery.

My `battery_charge` sensor mostly sits at 98% when full, and occasionally hits 100%. These are values taken straight from the battery so it's hard to give any further explaination.
