### ISSUE TITLE
Possible to add service options for Enable/Disabled Timed Discharge?

### ISSUE THREAD

**Issue by n1ghtwish** [cdpuk/givenergy-local#48]
I won't re-type all the stuff I put in my post, if anyone is interested it's [here](https://community.home-assistant.io/t/givenergy-solar-inverter/407844/136?u=n1ghtwish) and [here](https://community.home-assistant.io/t/givenergy-solar-inverter/407844/142?u=n1ghtwish).

The issue with the current available methods are that Activate Eco mode disables Timed Discharge, and Activate Timed Discharge disables Eco mode.

To have both enabled at once to prevent the battery from charging in the Timed Discharge window, it's necessary to Enable eco mode first, and then enable Timed Discharge in general. When done without adjusting times and just turning the option on, this runs the battery differently to how Timed Discharge or Eco Mode work separately.

The behaviour this appears to enable is that during Flux peak, the battery will stop charging, and will feed the house load with solar. Any excess solar will be exported. With just Eco Mode enabled, or Timed Discharge without Eco Mode, the battery is not prevented from charging.

**Comment by cdpuk** [comment]
I think everything should be available as of v1.8.0. In addition to the services, the low-level switches for Eco/Dynamic and Battery Discharging are also now exposed.

Bear in mind the definitions of the modes as set via the portal or app are:
`battery_power_mode=1, enable_discharge=1 => Timed Discharge`
`battery_power_mode=0, enable_discharge=1 => Timed Export`
`battery_power_mode=1, enable_discharge=0 => Eco/Dynamic`

Where `battery_power_mode` maps to "Enable Eco Mode" on the Remote Control page on the GE portal and `sensor.battery_eco_mode` in the integration. Confusingly the high-level Eco controls as seen elsewhere in the portal and app will also set `enable_discharge=0`.

Added #55 as a note for myself to write this down properly.
