### ISSUE TITLE
Suggestion: Add additional model to "Compatible with"

### ISSUE THREAD

**Issue by digdilem** [cdpuk/givenergy-local#5]
Firstly, thanks for writing and making this available. I've been using it for three weeks on my new install and it's been 100% perfect.

I can confirm that it works with at least one additional model of inverter and battery. 

Inverter: HY3.6
Battery: Giv-Bat5.2

The docs only mention one model, so my suggestion is that the above is added to the "Known to be working with" list.

Thanks again

![image](https://user-images.githubusercontent.com/4052275/179391461-83bc274b-cf50-4d0c-bf44-948a7f8e3397.png)

![image](https://user-images.githubusercontent.com/4052275/179391479-f698dec4-98f7-4226-95b1-a8db00f3fd39.png)

![image](https://user-images.githubusercontent.com/4052275/179391429-8fcee766-b93a-40bf-937d-b67698b82af0.png)

**Comment by cdpuk** [comment]
Hi, thanks for the feedback 😄 

I actually very recently removed the list of supported models as it felt like too much of a moving target to keep up to date. At the moment it seems the product range is fairly consistent so most (all?) inverters will work.

One area I'm keen for input on is the behaviour of different battery packs on newer inverters. The challenge here is they have different capabilities when it comes to things like charge/discharge power. The recently added sensors and services to set these are based on my Gen1 inverter with 8.2kWh battery, so I'm not sure how they will behave with others. Something to keep an eye on - I'm really just waiting for someone to raise an issue related to this so we can work though the logic.

![image](https://user-images.githubusercontent.com/24318424/179422472-eb2027b5-7657-41e7-81db-e491a00c45fb.png)
