### ISSUE TITLE
The "PV Power" sensor is unavailable on the Home Assistant Energy dashboard

### ISSUE THREAD

**Issue by michaelmarconi** [cdpuk/givenergy-local#57]
Hi, your GE Local integration is working beautifully, however the sensor `pv_power` doesn't appear to available as a sensor when I try to use it to configure my solar panels in the Home Assistant Energy dashboard (see image describing available sensors below).

<img width="499" alt="Configure solar panels screenshot" src="https://github.com/cdpuk/givenergy-local/assets/301715/6888bdc8-b04f-421a-a43d-cf6f849e744f">

The HA dropdown suggests pointing you to https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics, however I've taken a look at the code and spotted the `state_class` in the sensors defined at:  https://github.com/cdpuk/givenergy-local/blob/42410fa02b826a99f92515cfecca44a7a15000a6/custom_components/givenergy_local/sensor.py#L150

Have you been able to use your integration to power the Energy dashboard?

**Comment by cdpuk** [comment]
The HA energy dashboard only supports _energy_ values, not _power_ values. Your screenshot shows the "PV Energy" sensors for this reason. Some of my config:
![image](https://github.com/cdpuk/givenergy-local/assets/24318424/6ed21755-741b-45d9-88f7-3f1a77843d11)
