### ISSUE TITLE
Disable eco mode

### ISSUE THREAD

**Issue by grantstephens** [cdpuk/givenergy-local#66]
**Is your feature request related to a problem? Please describe.**
There is no way to disable eco mode or enable charging with excess solar, but disable discharging. The idea being to charge the battery as much as possible during the day (And use grid power if there isn't enough solar) and then turn on eco mode during peak time.

**Describe the solution you'd like**
It looks like the modbus library has a couple of options here, i.e. `disable_discharge` and `enable_charge` which would let you charge the battery up and you can activate eco mode during peak hours.
**Describe alternatives you've considered**
I don't think this is possible at the moment and don't think it can even be done via the cloud interface. At this stage I can disable eco mode via the cloud interface and then enable it via HA during peak time.
**Additional context**
On certain tariff options the 4-7pm times are very expensive and so charging/keeping the battery as full as possible during the day and then using eco mode during that time would minimize the bill. On some days there isn't enough sun to keep the battery at 100% during the day, especially with a heatpump, thus keeping it at close to full so that you minimize the peak time use makes more sense.

**Comment by cdpuk** [comment]
Sadly all these modes and switches are quite tricky to unpick, but what you want to do is certainly achievable.  I've just taken this chance to write up a bit more about what all the various controls do. This is still a bit of guesswork, as behaviour can vary across devices, the names of settings doesn't necessarily explain what they do, and GivEnergy themselves don't document these things particularly well.

https://github.com/cdpuk/givenergy-local/blob/master/docs/controls.md

Beware the "enable dischage" function does not necessarily disable discharging when off! The easiest way to achieve what you want, and the approach I use, is to set the charge & discharge power limits as required.
