### ISSUE TITLE
Moving my GivEnergy inverter IP address?

### ISSUE THREAD

**Issue by mprowe** [cdpuk/givenergy-local#9]
I have your Givenergy-local (ver 1.3.2) installed and working. Thank you for your magnificent  efforts...

Unfortunately, I did not plan far enough ahead and only have the inverter IP address defined by DHCP.
I would now like to give it a static address up with the other servers in my network.

My guess is that once I do that, givenergy-local will not be able to find the inverter?
How can I make givenergy-local request the new IP address  again?

Regards, M.

**Comment by cdpuk** [comment]
You will simply need to remove and re-add the integration using the new address during the setup process. The good news is that the inverter is identified by serial number in HA, so your entity history should all be preserved.
